# Generated by Django 2.0.5 on 2018-05-29 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsystem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionsystem',
            name='price',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionsystem',
            name='status',
            field=models.CharField(default='good', max_length=100),
            preserve_default=False,
        ),
    ]
