# Generated by Django 2.0.5 on 2018-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20180529_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsystem',
            name='item',
            field=models.ForeignKey(on_delete=None, to='item_list.ItemList'),
        ),
    ]
