# Generated by Django 2.0.5 on 2018-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysystem',
            name='Item',
            field=models.ForeignKey(on_delete=None, to='item_list.ItemList'),
        ),
    ]
