# Generated by Django 2.0.5 on 2018-05-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180529_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorysystem',
            old_name='Item',
            new_name='item',
        ),
    ]
