# Generated by Django 2.0.5 on 2018-06-03 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '__first__'),
        ('inventory', '0003_auto_20180529_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysystem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_list.ItemList'),
        ),
    ]
